import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { QueryClientProvider } from "react-query";
import queryClient from "@/utils/queryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {/* <QueryClientProvider client={queryClient}> */}
            {children}
          {/* </QueryClientProvider> */}
        </SessionProvider>
      </body>
    </html>
  );
}
